//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class conferencePaperProceeding
    {
        public int StaffMemNum { get; set; }
        public int ConferencePaperID { get; set; }
        public Nullable<int> ConferenceType { get; set; }
        public string Conference { get; set; }
        public string papeTitle { get; set; }
        public string authors { get; set; }
        public string place { get; set; }
        public Nullable<System.DateTime> from { get; set; }
        public Nullable<System.DateTime> to { get; set; }
        public Nullable<int> Year { get; set; }
        public string Proceeding { get; set; }
    
        public virtual ConferenceType ConferenceType1 { get; set; }
        public virtual Main Main { get; set; }
        public virtual Year Year1 { get; set; }
    }
}
