//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DissertationsSupervised
    {
        public int StaffMemNum { get; set; }
        public int DissertationsSupervisedID { get; set; }
        public Nullable<int> DissertationsSupervisedType { get; set; }
        public string Project_title { get; set; }
        public Nullable<int> year { get; set; }
        public string institute { get; set; }
    
        public virtual DissertationsSupervisedType DissertationsSupervisedType1 { get; set; }
        public virtual Main Main { get; set; }
        public virtual Year Year1 { get; set; }
    }
}
