//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAttended
    {
        public int StaffMemNum { get; set; }
        public int EventsAttendedID { get; set; }
        public Nullable<int> EventsAttendedType { get; set; }
        public string Title { get; set; }
        public string Organization { get; set; }
        public string Place { get; set; }
        public Nullable<System.DateTime> from { get; set; }
        public Nullable<System.DateTime> to { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual EventsAttendedType EventsAttendedType1 { get; set; }
        public virtual Main Main { get; set; }
        public virtual Year Year1 { get; set; }
    }
}
