//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funding
    {
        public int StaffMemNum { get; set; }
        public int fundingID { get; set; }
        public string ResearchTitle { get; set; }
        public string Sponser { get; set; }
        public Nullable<int> year { get; set; }
        public string amount { get; set; }
        public string description { get; set; }
        public Nullable<int> FundingNo { get; set; }
    
        public virtual Main Main { get; set; }
        public virtual Year Year1 { get; set; }
    }
}
