//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HonorsAndAward
    {
        public int StaffMemNum { get; set; }
        public int Award_id { get; set; }
        public Nullable<int> Award { get; set; }
        public string Organization { get; set; }
        public Nullable<int> Year { get; set; }
        public string Amount { get; set; }
        public string description { get; set; }
    
        public virtual Award Award1 { get; set; }
        public virtual Main Main { get; set; }
        public virtual Year Year1 { get; set; }
    }
}
