//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Main()
        {
            this.AcademicQualifications = new HashSet<AcademicQualification>();
            this.Assignments = new HashSet<Assignment>();
            this.Books = new HashSet<Book>();
            this.conferencePaperProceedings = new HashSet<conferencePaperProceeding>();
            this.DissertationsSuperviseds = new HashSet<DissertationsSupervised>();
            this.EventAttendeds = new HashSet<EventAttended>();
            this.Fundings = new HashSet<Funding>();
            this.HonorsAndAwards = new HashSet<HonorsAndAward>();
            this.InvitedLectures = new HashSet<InvitedLecture>();
            this.LevelDegrees = new HashSet<LevelDegree>();
            this.ProfessionalAffiliationMemberships = new HashSet<ProfessionalAffiliationMembership>();
            this.ProfessionalExperinces = new HashSet<ProfessionalExperince>();
            this.Publications = new HashSet<Publication>();
            this.PublicationsInReferredJournals = new HashSet<PublicationsInReferredJournal>();
            this.Referees = new HashSet<Referee>();
            this.ScholarshipsDetails = new HashSet<ScholarshipsDetail>();
            this.Services = new HashSet<Service>();
            this.Technicalreports = new HashSet<Technicalreport>();
        }
    
        public int StaffMemNum { get; set; }
        public string Name { get; set; }
        public Nullable<int> Citizenship { get; set; }
        public Nullable<int> Occupation { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string PlaceofBirth { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string Address { get; set; }
        public string ContactNum { get; set; }
        public string Email { get; set; }
        public string Web_Page { get; set; }
        public Nullable<int> PassportCountry { get; set; }
        public string PassportNo { get; set; }
        public string WorkCity { get; set; }
        public Nullable<System.DateTime> FirstDateHirig { get; set; }
        public Nullable<System.DateTime> FirstDateTabuk { get; set; }
        public Nullable<int> OffBuidling { get; set; }
        public Nullable<int> OfficeNo { get; set; }
        public Nullable<int> OfficeTrNo { get; set; }
        public string ResidenceNationalNo { get; set; }
        public string Photo { get; set; }
        public string Docs_certificates_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicQualification> AcademicQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Books { get; set; }
        public virtual Citizenship Citizenship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conferencePaperProceeding> conferencePaperProceedings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DissertationsSupervised> DissertationsSuperviseds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventAttended> EventAttendeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funding> Fundings { get; set; }
        public virtual Gender Gender1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HonorsAndAward> HonorsAndAwards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvitedLecture> InvitedLectures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LevelDegree> LevelDegrees { get; set; }
        public virtual MaritalState MaritalState { get; set; }
        public virtual Occupation Occupation1 { get; set; }
        public virtual OffBuidling OffBuidling1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessionalAffiliationMembership> ProfessionalAffiliationMemberships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessionalExperince> ProfessionalExperinces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicationsInReferredJournal> PublicationsInReferredJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referee> Referees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipsDetail> ScholarshipsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Technicalreport> Technicalreports { get; set; }
    }
}
