//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COMPUTERIZED_STATISTICAL_ROOM2Entities : DbContext
    {
        public COMPUTERIZED_STATISTICAL_ROOM2Entities()
            : base("name=COMPUTERIZED_STATISTICAL_ROOM2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicQualification> AcademicQualifications { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Citizenship> Citizenships { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<conferencePaperProceeding> conferencePaperProceedings { get; set; }
        public virtual DbSet<ConferenceType> ConferenceTypes { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<DissertationsSupervised> DissertationsSuperviseds { get; set; }
        public virtual DbSet<DissertationsSupervisedType> DissertationsSupervisedTypes { get; set; }
        public virtual DbSet<EditionalRole> EditionalRoles { get; set; }
        public virtual DbSet<EventAttended> EventAttendeds { get; set; }
        public virtual DbSet<EventsAttendedType> EventsAttendedTypes { get; set; }
        public virtual DbSet<Funding> Fundings { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GeneralSpecialization> GeneralSpecializations { get; set; }
        public virtual DbSet<HonorsAndAward> HonorsAndAwards { get; set; }
        public virtual DbSet<InvitedLecture> InvitedLectures { get; set; }
        public virtual DbSet<levedegreeType> levedegreeTypes { get; set; }
        public virtual DbSet<LevelDegree> LevelDegrees { get; set; }
        public virtual DbSet<Main> Mains { get; set; }
        public virtual DbSet<MaritalState> MaritalStates { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<OffBuidling> OffBuidlings { get; set; }
        public virtual DbSet<ProfessionalAffiliationMembership> ProfessionalAffiliationMemberships { get; set; }
        public virtual DbSet<ProfessionalExperince> ProfessionalExperinces { get; set; }
        public virtual DbSet<ProfessionalExperinceType> ProfessionalExperinceTypes { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<PublicationsInReferredJournal> PublicationsInReferredJournals { get; set; }
        public virtual DbSet<PublicationsType> PublicationsTypes { get; set; }
        public virtual DbSet<Referee> Referees { get; set; }
        public virtual DbSet<ScholarshipCase> ScholarshipCases { get; set; }
        public virtual DbSet<ScholarshipsDetail> ScholarshipsDetails { get; set; }
        public virtual DbSet<schoolardegree> schoolardegrees { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServicesScope> ServicesScopes { get; set; }
        public virtual DbSet<society> societies { get; set; }
        public virtual DbSet<SpecificSpecialization> SpecificSpecializations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Technicalreport> Technicalreports { get; set; }
        public virtual DbSet<Year> Years { get; set; }
    }
}
