//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalExperince
    {
        public int StaffMemNum { get; set; }
        public int ProfessionalExperianceID { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string orgnization { get; set; }
        public string address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> occupation { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProfessionalExperinceType { get; set; }
    
        public virtual Main Main { get; set; }
        public virtual Occupation Occupation1 { get; set; }
        public virtual ProfessionalExperinceType ProfessionalExperinceType1 { get; set; }
    }
}
