//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipsDetail
    {
        public int StaffMemNum { get; set; }
        public int ScholarshipID { get; set; }
        public Nullable<int> ScholarshipDegree { get; set; }
        public Nullable<int> ScholarshipCountry { get; set; }
        public Nullable<int> GeneralSpecialization { get; set; }
        public Nullable<int> SpecificSpecialization { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ScholarshipLetterNumber { get; set; }
        public Nullable<int> Case { get; set; }
    
        public virtual Case Case1 { get; set; }
        public virtual GeneralSpecialization GeneralSpecialization1 { get; set; }
        public virtual Main Main { get; set; }
        public virtual ScholarshipCase ScholarshipCase { get; set; }
        public virtual schoolardegree schoolardegree { get; set; }
        public virtual SpecificSpecialization SpecificSpecialization1 { get; set; }
    }
}
