//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPUTERIZED_STATISTICAL_ROOM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int StaffMemNum { get; set; }
        public int ServiceID { get; set; }
        public string ServicesName { get; set; }
        public string Task { get; set; }
        public Nullable<int> ServicesScope { get; set; }
        public string orgnization { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string description { get; set; }
    
        public virtual Main Main { get; set; }
        public virtual ServicesScope ServicesScope1 { get; set; }
    }
}
